gnome-terminal -e 'python a_control_node.py'
gnome-terminal -e 'python display_node.py'
gnome-terminal -e 'python b_control_node.py'
gnome-terminal -e 'python c_control_node.py'
#gnome-terminal -e 'python a_tree_control_node.py'
